### ISSUE TITLE
Render PDF with GH action

### ISSUE THREAD

**Issue by nuest** [o2r-project/architecture#11]
Remove usage of Travis CI

**Comment by Fmazin** [comment]
I have made a GH action which can theoretically can do every thing which the old travis could. But unfortunately the .gitignore blocks the `site` folder which screws with the github action doesn't upload its content to the gh-pages. Can i remove the gitignore for this purpose?

**Comment by nuest** [comment]
Don't remove the gitignore file, but un-ignore the PDF file: https://stackoverflow.com/questions/32504123/unignore-specific-files-in-subdirectory-with-gitignore

**Comment by Fmazin** [comment]
This fixes the problem. But i have a another question. In the old travis.yml the website contents and the PDF are created at same time. But now it would only update the pdf on a push to the master branch while the website would stay the same if we disable travis. Is this where we want to go?

**Comment by nuest** [comment]
It's fine to have two commits. Is that what you mean?

**Comment by Fmazin** [comment]
No the problem is that the gitignore still blocks the rest of the site folder from any commit, so the website isn't updated at all. And if we remove the site folder from the gitignore that file is empty.
